### ISSUE TITLE
Nimae description is wrong

### ISSUE THREAD

**Issue by f3mshep** [aquadrizzt/THavalon#1]
The Nimae description indicates she is seen by Merlin as evil. The README rules do not mention this.

**Comment by aquadrizzt** [comment]
Thanks for catching this. We flipflop'd on whether she should be seen by Merlin as Evil or not for a while. She isn't and should not be. Looking at the code we correctly updated Merlin's information generation but didn't fix Nimue's description string when we made the change. I'll fix it right now.
